{% set name = "jkqtplotter" %}
{% set version = "2019.11.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jkriege2/JKQtPlotter/archive/v{{ version }}.tar.gz
  sha256: 4fb77163b5067afda1cb4e08176e3c9d5289a9f63a483638f6ebd4a9c1ce9d70

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja   # [win]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('libselinux') }}            # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('libxext') }}               # [linux]
    - {{ cdt('xorg-x11-server-xvfb') }}  # [linux]
    - {{ cdt('libxau') }}                # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
  host:
    - qt
  run:
    - qt

test:
  commands:
    - test -f $PREFIX/lib/libJKQTPlotterSharedLib_Release.so    # [linux]
    - test -f $PREFIX/lib/libJKQTPlotterSharedLib_Release.dylib    # [osx]
    - if exist %LIBRARY_PREFIX%\lib\JKQTPlotterSharedLib_Release.lib (exit 0) else (exit 1)    # [win]

about:
  home: https://github.com/jkriege2/JKQtPlotter
  license: LGPL
  license_file:
    - LICENSE
    - lib/jkqtmathtext/resources/xits/OFL.txt
  summary: An extensive library of function/data plotter classes for Qt

  description: |
    An extensive Qt4/Qt5 Plotter framework (including a fast variant and a
    LaTeX equation renderer), written fully in C/C++ and without external
    dependencies.
  doc_url: http://jkriege2.github.io/JKQtPlotter/index.html
  dev_url: https://github.com/jkriege2/JKQtPlotter

extra:
  recipe-maintainers:
    - certik
